# Generated by Django 4.1.7 on 2023-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(verbose_name="Номер заказа"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Стоимость в $$")),
                ("delivery_time", models.DateTimeField(verbose_name="Срок поставки")),
            ],
        ),
    ]
