# Generated by Django 4.1.7 on 2023-03-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_delivery_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
    ]
