# Generated by Django 4.1.7 on 2023-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price_rub",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Стоимость в Rub"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="price_usd",
            field=models.PositiveIntegerField(default=1, verbose_name="Стоимость в $"),
            preserve_default=False,
        ),
    ]
